### ISSUE TITLE
data sets

### ISSUE THREAD

**Issue by gansu-yimi** [Wang-ML-Lab/VDI#2]
Hello, thank you very much for your work. I would like to go ahead and reproduce this work and would like to ask you how the dataset should be obtained. Looking forward to your reply!

**Comment by shsjxzh** [comment]
Hi happy,

Sorry for the late response! All the datasets are included in this repository:
Toy: "Toy/data" folder
TPT-48: "TPT-48/train_data/data" folder
CompCars: "CompCars/data" folder

If you mean the source of all these datasets, then:
Toy dataset is generated by ourselves.
TPT-48 comes from [Washington Post](https://github.com/washingtonpost/data-2C-beyond-the-limit-usa).
CompCars comes from [MMLab](http://mmlab.ie.cuhk.edu.hk/datasets/comp_cars/).

Best,
shsjxzh
