### ISSUE TITLE
Model Evaluation

### ISSUE THREAD

**Issue by KinTorch** [Wang-ML-Lab/VDI#3]
Hello. Thanks for the impressive work. I'm curious about the methods used for model evaluation and selection, like validation data partitioning, which weren't detailed in the paper. Would you mind sharing some details on these processes?

**Comment by shsjxzh** [comment]
Hi KinTorch,

Thank you for your attention! For convenience, we test our model on **all** the target domain data. For CompCars and Toy, the evaluation metric is the accuracy, while for the TPT-48, it is the mean square error.

Best,
Zihao

**Comment by KinTorch** [comment]
Thank you for your quick response! I appreciate the insights. Just to further understand, could you please share the approach used to decide on the epoch to use for evaluation. Did you consider any additional metrics or choose a specific fixed epoch?

**Comment by shsjxzh** [comment]
I choose a specific fixed epoch. It is controled by the "test_interval" in the configuration (see "configs" folder in each experiment). You can also check the "main.py" for more details.

**Comment by KinTorch** [comment]
Understood. Thank you for replying.
